# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/lawrence/StudyDrive/Hoc DH/HKI-2018-2019/DigitalImageProcessing/exercises/1512203_Lab05/DIP-HW05"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/lawrence/StudyDrive/Hoc DH/HKI-2018-2019/DigitalImageProcessing/exercises/1512203_Lab05/DIP-HW05"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/lawrence/StudyDrive/Hoc DH/HKI-2018-2019/DigitalImageProcessing/exercises/1512203_Lab05/DIP-HW05/CMakeFiles" "/media/lawrence/StudyDrive/Hoc DH/HKI-2018-2019/DigitalImageProcessing/exercises/1512203_Lab05/DIP-HW05/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/lawrence/StudyDrive/Hoc DH/HKI-2018-2019/DigitalImageProcessing/exercises/1512203_Lab05/DIP-HW05/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DIP_HW05

# Build rule for target.
DIP_HW05: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DIP_HW05
.PHONY : DIP_HW05

# fast build rule for target.
DIP_HW05/fast:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/build
.PHONY : DIP_HW05/fast

src/BaseProcessor.o: src/BaseProcessor.cpp.o

.PHONY : src/BaseProcessor.o

# target to build an object file
src/BaseProcessor.cpp.o:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/BaseProcessor.cpp.o
.PHONY : src/BaseProcessor.cpp.o

src/BaseProcessor.i: src/BaseProcessor.cpp.i

.PHONY : src/BaseProcessor.i

# target to preprocess a source file
src/BaseProcessor.cpp.i:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/BaseProcessor.cpp.i
.PHONY : src/BaseProcessor.cpp.i

src/BaseProcessor.s: src/BaseProcessor.cpp.s

.PHONY : src/BaseProcessor.s

# target to generate assembly for a file
src/BaseProcessor.cpp.s:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/BaseProcessor.cpp.s
.PHONY : src/BaseProcessor.cpp.s

src/EdgeDetector.o: src/EdgeDetector.cpp.o

.PHONY : src/EdgeDetector.o

# target to build an object file
src/EdgeDetector.cpp.o:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/EdgeDetector.cpp.o
.PHONY : src/EdgeDetector.cpp.o

src/EdgeDetector.i: src/EdgeDetector.cpp.i

.PHONY : src/EdgeDetector.i

# target to preprocess a source file
src/EdgeDetector.cpp.i:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/EdgeDetector.cpp.i
.PHONY : src/EdgeDetector.cpp.i

src/EdgeDetector.s: src/EdgeDetector.cpp.s

.PHONY : src/EdgeDetector.s

# target to generate assembly for a file
src/EdgeDetector.cpp.s:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/EdgeDetector.cpp.s
.PHONY : src/EdgeDetector.cpp.s

src/common.o: src/common.cpp.o

.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/filters/BaseFilters.o: src/filters/BaseFilters.cpp.o

.PHONY : src/filters/BaseFilters.o

# target to build an object file
src/filters/BaseFilters.cpp.o:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/filters/BaseFilters.cpp.o
.PHONY : src/filters/BaseFilters.cpp.o

src/filters/BaseFilters.i: src/filters/BaseFilters.cpp.i

.PHONY : src/filters/BaseFilters.i

# target to preprocess a source file
src/filters/BaseFilters.cpp.i:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/filters/BaseFilters.cpp.i
.PHONY : src/filters/BaseFilters.cpp.i

src/filters/BaseFilters.s: src/filters/BaseFilters.cpp.s

.PHONY : src/filters/BaseFilters.s

# target to generate assembly for a file
src/filters/BaseFilters.cpp.s:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/filters/BaseFilters.cpp.s
.PHONY : src/filters/BaseFilters.cpp.s

src/filters/GradientFilters.o: src/filters/GradientFilters.cpp.o

.PHONY : src/filters/GradientFilters.o

# target to build an object file
src/filters/GradientFilters.cpp.o:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/filters/GradientFilters.cpp.o
.PHONY : src/filters/GradientFilters.cpp.o

src/filters/GradientFilters.i: src/filters/GradientFilters.cpp.i

.PHONY : src/filters/GradientFilters.i

# target to preprocess a source file
src/filters/GradientFilters.cpp.i:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/filters/GradientFilters.cpp.i
.PHONY : src/filters/GradientFilters.cpp.i

src/filters/GradientFilters.s: src/filters/GradientFilters.cpp.s

.PHONY : src/filters/GradientFilters.s

# target to generate assembly for a file
src/filters/GradientFilters.cpp.s:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/filters/GradientFilters.cpp.s
.PHONY : src/filters/GradientFilters.cpp.s

src/filters/SobelFilter.o: src/filters/SobelFilter.cpp.o

.PHONY : src/filters/SobelFilter.o

# target to build an object file
src/filters/SobelFilter.cpp.o:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/filters/SobelFilter.cpp.o
.PHONY : src/filters/SobelFilter.cpp.o

src/filters/SobelFilter.i: src/filters/SobelFilter.cpp.i

.PHONY : src/filters/SobelFilter.i

# target to preprocess a source file
src/filters/SobelFilter.cpp.i:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/filters/SobelFilter.cpp.i
.PHONY : src/filters/SobelFilter.cpp.i

src/filters/SobelFilter.s: src/filters/SobelFilter.cpp.s

.PHONY : src/filters/SobelFilter.s

# target to generate assembly for a file
src/filters/SobelFilter.cpp.s:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/filters/SobelFilter.cpp.s
.PHONY : src/filters/SobelFilter.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/DIP_HW05.dir/build.make CMakeFiles/DIP_HW05.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DIP_HW05"
	@echo "... src/BaseProcessor.o"
	@echo "... src/BaseProcessor.i"
	@echo "... src/BaseProcessor.s"
	@echo "... src/EdgeDetector.o"
	@echo "... src/EdgeDetector.i"
	@echo "... src/EdgeDetector.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/filters/BaseFilters.o"
	@echo "... src/filters/BaseFilters.i"
	@echo "... src/filters/BaseFilters.s"
	@echo "... src/filters/GradientFilters.o"
	@echo "... src/filters/GradientFilters.i"
	@echo "... src/filters/GradientFilters.s"
	@echo "... src/filters/SobelFilter.o"
	@echo "... src/filters/SobelFilter.i"
	@echo "... src/filters/SobelFilter.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

